config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts
  root "posts#index"
  resources :zines do
    collection do
	  post '/:id/user_private' => 'zines#user_private'
    end
  end
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :zine

  with_options presence: true do
    validates :year, :month
    validates :url
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :zines
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
  validates :email, :image
  validates :nickname, length: { maximum: 6 }
  end
end

app/models/zine.rb
class Zine < ApplicationRecord
  belongs_to :user
  has_many :posts
  validates :year, :month, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    t = Time.new
    if Zine.where(month: t.month).where(year: t.year).where(user_id: current_user.id).exists?
      @zine = Zine.find_by(month: t.month, year: t.year, user_id: current_user.id)
    else
      @zine = Zine.new
      @zine = Zine.create(zine_params)
    end
    redirect_to controller: :zines, action: :show, id: @zine.id
  end

  def create
    t = Time.new
    @zine = Zine.where(month: t.month).where(year: t.year).where(user_id: current_user.id)
    @post = Post.new(post_params)
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def zine_params
    t = Time.new
    params.permit(:release).merge(user_id: current_user.id, month: t.month, year: t.year)
  end

  def post_params
    t = Time.new
    params.permit(:url).merge(user_id: current_user.id, month: t.month, year: t.year, zine_id: @zine.ids[0])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :image, :email)
  end
end

app/controllers/zines_controller.rb
class ZinesController < ApplicationController
  def show
    @zines = Zine.where(user_id: current_user.id)
    @zine = Zine.find(params[:id])
    @post = Post.new
    @posts = @zine.posts.order("created_at DESC")
  end

  def user_private
    @zine = Zine.find(params[:id])
    @zine.private = !@zine.private # privates でなく private かも
    @zine.save # ここでuser_params使わないの？？？
  end

  def index
    @zines = Zine.where(private: false).order(created_at: :desc)
  end

  private

  def user_params
    params.require(:zine).permit(:private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/zines_helper.rb
module ZinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>月刊マイスクラップ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href=<%= '/images/logomark.png'%>>

    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- viewport meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%# 共通ヘッダー %>
<%= render "shared/header" %>

<%= render "shared/show" %>

app/views/shared/_header.html.erb
<style>
  body {
    min-height: 75rem;
    padding-top: 4.5rem;
  }
  .dropdown-toggle {
     position:relative;
  }
  .dropdown-menu {
  position:absolute;
  }
  .dropdown-menu {
  border: none;
  }
  .create {
    color:white ;
    background: #47BBBF;
    border: 1px solid #47BBBF;
  } 

  .header-avatar {
  object-fit: cover;
  width: 50px;
  height: 50px;
  }

</style>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top shadow" style="background-color:#BFBFBF">
  <%= link_to image_tag("/images/logo.png", width: '200', alt: "logo"),  root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon" ></span>
  </button>


  <div class="collapse navbar-collapse"  id="navbarCollapse">
    <ul class="navbar-nav mr-auto" >
      <% if @zine != nil %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
            <% if current_page?("/zines") %>
              公開スクラップ一覧
            <% elsif current_user == @zine.user %>
              <%=@zine.year %>年<%=@zine.month %>月号
            <% else %>
              <%=@zine.user.nickname %>さんの<br>
              <%=@zine.year %>年<%=@zine.month %>月号
            <% end %>
          </a>
          <div class="dropdown-menu text-light" style="background-color:#BFBFBF" aria-labelledby="navbarDropdownMenuLink">
            <h6 class="dropdown-header">MySCRAP</h6>
            <% @zines.each do |zine| %>
              <button class="dropdown-item text-light" href="#">
                <%= link_to "#{zine.year}年#{zine.month}月号", zine_path(zine.id), class: 'text-light'%>
              </button>
            <% end %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item text-light" href="/zines">
              公開SCRAP一覧
            </a>
          </div>
        </li>
      <% end %>

      <li class="nav-item dropdown">
        <a   href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= image_tag current_user.image, class: 'header-avatar rounded-circle', width: '30', height: '30' %>
        </a>
        <div class="dropdown-menu text-light" style="background-color:#BFBFBF" aria-labelledby="navbarDropdownMenuLink">
          <h6 class="dropdown-header"><%= current_user.nickname %></h6>
          <button class="dropdown-item">
          <%= link_to "編集", edit_user_registration_path %>
          </button>
          <button class="dropdown-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
          </button>
        </div>
 
      </li>





    </ul>
      <div class="form-inline mt-2 mt-lg-0">
        <%= form_with url: "/posts", method: :post, local: true do |f| %>
          <%= f.url_field :url, class: 'form-control mr-sm-2 font-italic', placeholder: 'URL' %>
          <%= f.submit 'SCRAP!', class: 'btn btn-success my-0 my-sm-0 create shadow  font-weight-bold font-italic' %>
        <% end %>
      </div>
  </div>
</nav>

<%# <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> %>
<%# <script>window.jQuery || document.write('<script src="../images/js/vendor/jquery.slim.min.js"><\/script>')</script> %>
<%# <script src="../images/dist/js/bootstrap.bundle.js"></script> %>

app/views/shared/_show.erb
<style>

  .col-lg-6 {
    margin:5px 0 
    position: relative;
  }
  svg {
    position: absolute;
    right: 3px;
    height: 10%;
    width: 10%;
    z-index:10;
  }
  .trashcan img{
    position: absolute;
    bottom:5%;
    right:3%;
    filter: drop-shadow(10px 10px 10px rgba(0,0,0,0.6));
    z-index:10;
    width: 7%;
  }
  
  .col-lg-6 img {
    width:100%;
    max-width: 100%;
    height: auto;
  }

  .img_wrap{
    margin: 0 auto;
    overflow: hidden;
    z-index:0;
  }
  .img_wrap .thumb img{
    width: 100%;
    transition-duration: 0.5s;
  }
  .img_wrap:hover img{
    transform: scale(1.08);
    opacity: 0.6;
    transition-duration: 0.5s;
  }
  .kanban {
    height:100vh;
  }

  .howto {
    margin-bottom:150px;
  }

</style>



<body class="container-frueid align-items-center">
  <% if current_user == @zine.user && !@zine.posts.empty?%>
    <p>
      <strong>PRIVATE</strong>
        <%= check_box_tag 'zine[private]', true, @zine[:private], {
          onchange: '$(this).data("params", "zine[private]=" + this.checked)',
            data: {
              url: zine_url + '/user_private/',
                method: :post,
                remote: true
            }
        } %>
    </p>
  <% end %>

  <% if @zine.posts.empty? %>

  <div class="container-frueid kanban align-items-center">
  
    <div class="row align-items-center justify-content-center no-gutters font-weight-bold font-italic" style="height:auto; margin-top:100px;">
      <div class="display-4 col-12 col-md-auto text-center">ようこそ</div>
      <div class="col col-md-auto text-center">
        <%= image_tag '/images/logo_big.png', style: 'width:200px;'%>
      </div>
      <div class="display-4 col-12 col-md-auto text-center">へ。</div>
    </div>
  
    <div class="row align-items-center font-weight-bold font-italic"style="height:100px; margin:100px 0 30px">  
      <div class="h3 col-lg text-center">操作は簡単、４ステップ！</div>
    </div>

    <div div class="row align-items-center no-gutters font-weight-bold" style="height:300px;">
    
      <div class="howto col-lg-6 col-xl-3 h-100 w-100 text-center">
        <div class="h1">
        1. COPY
        </div>
        <div class="h-100 d-flex align-items-center justify-content-center">
          <%= image_tag '/images/copy.png', style: 'width:150px;', class: ''%>
        </div>
        <div class="h6">
        <u>好きなページのURLをコピー。</u>
        </div>
      </div>
      
      <div class="howto col-lg-6 col-xl-3 h-100 w-100 text-center">
        <div class="h1">
        2. PASTE
        </div>
        <div class="h-100 d-flex align-items-center justify-content-center">
          <%= image_tag '/images/paste.png', style: 'width:150px;', class: ''%>
        </div>
        <div class="h6">
        <u>それをURL欄に貼り付け。</u>
        </div>
      </div>

      <div class="howto col-lg-6 col-xl-3 h-100 w-100 text-center">
        <div class="h1">
        3. SAVE
        </div>
        <div class="h-100 d-flex align-items-center justify-content-center">
          <%= image_tag '/images/scrap.png', style: 'width:200px;', class: ''%>
        </div>
        <div class="h6">
        <u>"SCRAP!"ボタンで保存完了！</u>
        </div>
      </div>

      <div class="howto col-lg-6 col-xl-3 h-100 w-100 text-center">
        <div class="h1">
        4. SORT
        </div>
        <div class="h-100 d-flex align-items-center justify-content-center">
          <%= image_tag '/images/sort.png', style: 'width:200px;', class: ''%>
        </div>
        <div class="h6">
        <u>しおりを掴んでSCRAPの並び替えも。</u>
        </div>
      </div>

    </div>  
  </div>

  <% end %>

  <div>
    <div class="sortable row">
    <% @posts.each_with_index do |post,i| %>
      <div class="col-6 col-lg-4 rounded shadow img_wrap" style="color:#47BBBF;" id="<%=i%>">
      <% if current_user == @zine.user %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-bookmark-fill" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.74.439L8 13.069l-5.26 2.87A.5.5 0 0 1 2 15.5V2z"/>
        </svg> 
          <%= link_to image_tag("/images/trashcan.png"), post_path(post.id), method: :delete, class: 'trashcan'%>
      <% end %>
      <%= link_to image_tag(thumbalizr_url(post.url, {:country => 'ja', :width =>  960})), post.url, :target => "_blank", class: 'link thumb' %>
      </div>
    <% end %> 
    </div>
  </div>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>


<!-- jQuery UI -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>


<%# Sortable %>
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

<%# jQuery UI Touch Punch %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
<!-- jQuery cookie -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>


<%# sortable %>
<script type="text/javascript">
$(function() {
    $(".sortable").sortable({
          scroll: true,
          cursor: "move",
          handle: 'svg',
          tolerance: "pointer"
        });
    $(".sortable").disableSelection();
    $(".sortable").sortable({
        update: function(ev, ui) {
            var updateArray =  $(".sortable").sortable("toArray").join(",");
            $.cookie("sortable", updateArray, {expires: 30});
        }       
    });
    if($.cookie("sortable")) {
        var cookieValue = $.cookie("sortable").split(",").reverse();
        $.each(
            cookieValue,
            function(index, value) {$('#'+value).prependTo(".sortable");}
        );
    }
});
</script>

</body>

app/views/zines/index.html.erb
<head>
  <!-- Bootstrap core CSS -->
  <link href="../assets/dist/css/bootstrap.css" rel="stylesheet">
  <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }
  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  .card {
    position:relative;
  }
  .card img {
  object-fit: cover;
  width: 100%;
  }
  .card-text {
    width:100%;
    height:100%;
    text-align: center;
    position:absolute;
    left:0;
    top:0;
  }
  .img_wrap{
  border: 1px solid #ddd;
  margin: 0 auto;
  overflow: hidden;
  cursor: pointer;
}
.img_wrap img{
  width: 100%;
  transition-duration: 0.5s;
}
.img_wrap:hover img{
  transform: scale(1.2);
  opacity: 0.6;
  transition-duration: 0.5s;
}
  </style>
</head>
<body>

<%# 共通ヘッダー %>
<%= render "shared/header"%>

  <main role="main">
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row"> 
          <% @zines.each do |zine| %>
              <div class="col-md-12 col-lg-6">
                <div class="card mb-4 shadow-sm img_wrap">
                  <%= link_to zine_path(zine.id) do %>
                    <%=  image_tag zine.user.image, class:'card-img-top', width: '100%', height: '225'%>
                      <div class="card-text d-flex align-items-center justify-content-center text-white font-weight-bold font-italic">
                        <h1><strong><%= zine.user.nickname %>'s SCRAP<br>
                        <%= zine.year %>年<%= zine.month %>月号</h1></strong>
                      </div>
                  <% end %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</main>

app/views/zines/show.html.erb
<%# 共通ヘッダー %>
<%= render "shared/header"%>

<%# 記事リンク一覧 %>
<%= render "shared/show"%>